/** Generated from the original LaMelodiosa.sfz mapping. */
export type LaMelodiosaRegister = "I" | "II" | "III";
export type LaMelodiosaSide = "treble" | "bass";
export type LaMelodiosaRegion = { side: LaMelodiosaSide; register: LaMelodiosaRegister; lowMidi: number; highMidi: number; amplitude: number; samples: Array<{ file: string; rootMidi: number; tuneCents: number }>; };

export const LA_MELODIOSA_SAMPLE_BASE = `${import.meta.env.BASE_URL}samples/la-melodiosa/audio/`;

export const LA_MELODIOSA_REGIONS: LaMelodiosaRegion[] = [
  { side: "bass", register: "I", lowMidi: 48, highMidi: 50, amplitude: 100, samples: [{ file: "BS-Csharp5-ba.wav", rootMidi: 49, tuneCents: -3 }] },
  { side: "bass", register: "I", lowMidi: 55, highMidi: 56, amplitude: 100, samples: [{ file: "BS-Gsharp5-ba.wav", rootMidi: 56, tuneCents: -7 }] },
  { side: "bass", register: "I", lowMidi: 51, highMidi: 54, amplitude: 100, samples: [{ file: "BS-E5-ba.wav", rootMidi: 52, tuneCents: -3 }] },
  { side: "bass", register: "I", lowMidi: 57, highMidi: 59, amplitude: 100, samples: [{ file: "BS-A5-ba.wav", rootMidi: 57, tuneCents: -6 }] },
  { side: "bass", register: "II", lowMidi: 48, highMidi: 50, amplitude: 100, samples: [{ file: "BS-II-D4-ba.wav", rootMidi: 50, tuneCents: -7 }] },
  { side: "bass", register: "II", lowMidi: 55, highMidi: 57, amplitude: 100, samples: [{ file: "BS-II-A4-ba.wav", rootMidi: 57, tuneCents: -10 }] },
  { side: "bass", register: "II", lowMidi: 51, highMidi: 54, amplitude: 100, samples: [{ file: "BS-II-E4-ba.wav", rootMidi: 52, tuneCents: -4 }] },
  { side: "bass", register: "II", lowMidi: 58, highMidi: 59, amplitude: 100, samples: [{ file: "BS-II-B4-ba.wav", rootMidi: 59, tuneCents: -4 }] },
  { side: "bass", register: "III", lowMidi: 48, highMidi: 50, amplitude: 100, samples: [{ file: "BS-III-D4-ba.wav", rootMidi: 50, tuneCents: -4 }] },
  { side: "bass", register: "III", lowMidi: 55, highMidi: 57, amplitude: 100, samples: [{ file: "BS-III-A4-ba.wav", rootMidi: 57, tuneCents: 0 }] },
  { side: "bass", register: "III", lowMidi: 51, highMidi: 54, amplitude: 100, samples: [{ file: "BS-III-E4-ba.wav", rootMidi: 52, tuneCents: -4 }] },
  { side: "bass", register: "III", lowMidi: 58, highMidi: 59, amplitude: 100, samples: [{ file: "BS-III-B4-ba.wav", rootMidi: 59, tuneCents: -4 }] },
  { side: "bass", register: "I", lowMidi: 43, highMidi: 44, amplitude: 100, samples: [{ file: "BS-Gsharp5-ba.wav", rootMidi: 44, tuneCents: -4 }] },
  { side: "bass", register: "I", lowMidi: 39, highMidi: 42, amplitude: 100, samples: [{ file: "BS-E5-ba.wav", rootMidi: 40, tuneCents: -3 }] },
  { side: "bass", register: "I", lowMidi: 36, highMidi: 47, amplitude: 100, samples: [{ file: "BS-A5-ba.wav", rootMidi: 45, tuneCents: -6 }] },
  { side: "bass", register: "II", lowMidi: 43, highMidi: 45, amplitude: 100, samples: [{ file: "BS-II-A4-ba.wav", rootMidi: 45, tuneCents: -6 }] },
  { side: "bass", register: "II", lowMidi: 39, highMidi: 42, amplitude: 100, samples: [{ file: "BS-II-E4-ba.wav", rootMidi: 40, tuneCents: -4 }] },
  { side: "bass", register: "II", lowMidi: 36, highMidi: 47, amplitude: 100, samples: [{ file: "BS-II-B4-ba.wav", rootMidi: 47, tuneCents: 0 }] },
  { side: "bass", register: "III", lowMidi: 43, highMidi: 45, amplitude: 110, samples: [{ file: "BS-III-A4-ba.wav", rootMidi: 45, tuneCents: -6 }] },
  { side: "bass", register: "III", lowMidi: 39, highMidi: 42, amplitude: 100, samples: [{ file: "BS-III-E4-ba.wav", rootMidi: 40, tuneCents: -4 }] },
  { side: "bass", register: "III", lowMidi: 36, highMidi: 47, amplitude: 100, samples: [{ file: "BS-III-B4-ba.wav", rootMidi: 47, tuneCents: 0 }] },
  { side: "treble", register: "I", lowMidi: 60, highMidi: 64, amplitude: 145, samples: [{ file: "I-Dsharp4-ba.wav", rootMidi: 63, tuneCents: -6 }, { file: "I-Dsharp4-va.wav", rootMidi: 63, tuneCents: -6 }] },
  { side: "treble", register: "I", lowMidi: 65, highMidi: 67, amplitude: 140, samples: [{ file: "I-Fsharp4-ba.wav", rootMidi: 66, tuneCents: -6 }, { file: "I-Fsharp4-va.wav", rootMidi: 66, tuneCents: -6 }] },
  { side: "treble", register: "I", lowMidi: 68, highMidi: 70, amplitude: 150, samples: [{ file: "I-A4-ba.wav", rootMidi: 69, tuneCents: -7 }, { file: "I-A4-va.wav", rootMidi: 69, tuneCents: -7 }] },
  { side: "treble", register: "I", lowMidi: 71, highMidi: 74, amplitude: 140, samples: [{ file: "I-C5-ba.wav", rootMidi: 72, tuneCents: -4 }, { file: "I-C5-va.wav", rootMidi: 72, tuneCents: -4 }] },
  { side: "treble", register: "I", lowMidi: 75, highMidi: 76, amplitude: 150, samples: [{ file: "I-Dsharp5-ba.wav", rootMidi: 75, tuneCents: -5 }, { file: "I-Dsharp5-va.wav", rootMidi: 75, tuneCents: -5 }] },
  { side: "treble", register: "I", lowMidi: 77, highMidi: 79, amplitude: 180, samples: [{ file: "I-Fsharp5-ba.wav", rootMidi: 78, tuneCents: -5 }, { file: "I-Fsharp5-va.wav", rootMidi: 78, tuneCents: -5 }] },
  { side: "treble", register: "I", lowMidi: 80, highMidi: 82, amplitude: 150, samples: [{ file: "I-A5-ba.wav", rootMidi: 81, tuneCents: -8 }, { file: "I-A5-va.wav", rootMidi: 81, tuneCents: -8 }] },
  { side: "treble", register: "I", lowMidi: 83, highMidi: 85, amplitude: 150, samples: [{ file: "I-C6-ba.wav", rootMidi: 84, tuneCents: -9 }, { file: "I-C6-va.wav", rootMidi: 84, tuneCents: -9 }] },
  { side: "treble", register: "I", lowMidi: 86, highMidi: 88, amplitude: 170, samples: [{ file: "I-Dsharp6-ba.wav", rootMidi: 87, tuneCents: 0 }, { file: "I-Dsharp6-va.wav", rootMidi: 87, tuneCents: 0 }] },
  { side: "treble", register: "I", lowMidi: 89, highMidi: 91, amplitude: 170, samples: [{ file: "I-Fsharp6-ba.wav", rootMidi: 90, tuneCents: -4 }, { file: "I-Fsharp6-va.wav", rootMidi: 90, tuneCents: -4 }] },
  { side: "treble", register: "I", lowMidi: 92, highMidi: 94, amplitude: 180, samples: [{ file: "I-A6-ba.wav", rootMidi: 93, tuneCents: 0 }, { file: "I-A6-va.wav", rootMidi: 93, tuneCents: 0 }] },
  { side: "treble", register: "I", lowMidi: 95, highMidi: 96, amplitude: 180, samples: [{ file: "I-C7-ba.wav", rootMidi: 96, tuneCents: 0 }, { file: "I-C7-va.wav", rootMidi: 96, tuneCents: 0 }] },
  { side: "treble", register: "II", lowMidi: 60, highMidi: 65, amplitude: 150, samples: [{ file: "II-Dsharp4-ba.wav", rootMidi: 63, tuneCents: 2 }, { file: "II-Dsharp4-va.wav", rootMidi: 63, tuneCents: 2 }] },
  { side: "treble", register: "II", lowMidi: 66, highMidi: 67, amplitude: 140, samples: [{ file: "II-Fsharp4-ba.wav", rootMidi: 66, tuneCents: 0 }, { file: "II-Fsharp4-va.wav", rootMidi: 66, tuneCents: 0 }] },
  { side: "treble", register: "II", lowMidi: 68, highMidi: 70, amplitude: 150, samples: [{ file: "II-A4-ba.wav", rootMidi: 69, tuneCents: 0 }, { file: "II-A4-va.wav", rootMidi: 69, tuneCents: 0 }] },
  { side: "treble", register: "II", lowMidi: 71, highMidi: 74, amplitude: 140, samples: [{ file: "II-C5-va.wav", rootMidi: 72, tuneCents: 3 }, { file: "II-C5-va.wav", rootMidi: 72, tuneCents: 3 }] },
  { side: "treble", register: "II", lowMidi: 75, highMidi: 76, amplitude: 140, samples: [{ file: "II-Dsharp5-ba.wav", rootMidi: 75, tuneCents: -7 }, { file: "II-Dsharp5-va.wav", rootMidi: 75, tuneCents: -7 }] },
  { side: "treble", register: "II", lowMidi: 77, highMidi: 79, amplitude: 180, samples: [{ file: "II-Fsharp5-ba.wav", rootMidi: 78, tuneCents: -4 }, { file: "II-Fsharp5-va.wav", rootMidi: 78, tuneCents: -4 }] },
  { side: "treble", register: "II", lowMidi: 80, highMidi: 82, amplitude: 170, samples: [{ file: "II-A5-ba.wav", rootMidi: 81, tuneCents: -4 }, { file: "II-A5-va.wav", rootMidi: 81, tuneCents: -4 }] },
  { side: "treble", register: "II", lowMidi: 83, highMidi: 85, amplitude: 115, samples: [{ file: "II-C6-ba.wav", rootMidi: 84, tuneCents: -5 }, { file: "II-C6-va.wav", rootMidi: 84, tuneCents: -5 }] },
  { side: "treble", register: "II", lowMidi: 86, highMidi: 88, amplitude: 170, samples: [{ file: "II-Dsharp6-ba.wav", rootMidi: 87, tuneCents: -1 }, { file: "II-Dsharp6-va.wav", rootMidi: 87, tuneCents: -1 }] },
  { side: "treble", register: "II", lowMidi: 89, highMidi: 91, amplitude: 180, samples: [{ file: "II-Fsharp6-ba.wav", rootMidi: 90, tuneCents: -4 }, { file: "II-Fsharp6-va.wav", rootMidi: 90, tuneCents: -4 }] },
  { side: "treble", register: "II", lowMidi: 92, highMidi: 94, amplitude: 170, samples: [{ file: "II-A6-ba.wav", rootMidi: 93, tuneCents: -7 }, { file: "II-A6-va.wav", rootMidi: 93, tuneCents: -7 }] },
  { side: "treble", register: "II", lowMidi: 95, highMidi: 96, amplitude: 170, samples: [{ file: "II-C7-ba.wav", rootMidi: 96, tuneCents: -7 }, { file: "II-C7-va.wav", rootMidi: 96, tuneCents: -7 }] },
  { side: "treble", register: "III", lowMidi: 60, highMidi: 64, amplitude: 140, samples: [{ file: "III-Dsharp4-ba.wav", rootMidi: 63, tuneCents: 4 }, { file: "III-Dsharp4-va.wav", rootMidi: 63, tuneCents: 4 }] },
  { side: "treble", register: "III", lowMidi: 65, highMidi: 67, amplitude: 140, samples: [{ file: "III-Fsharp4-ba.wav", rootMidi: 66, tuneCents: 0 }, { file: "III-Fsharp4-va.wav", rootMidi: 66, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 68, highMidi: 70, amplitude: 140, samples: [{ file: "III-A4-ba.wav", rootMidi: 69, tuneCents: 0 }, { file: "III-A4-va.wav", rootMidi: 69, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 71, highMidi: 74, amplitude: 140, samples: [{ file: "III-C5-ba.wav", rootMidi: 72, tuneCents: 0 }, { file: "III-C5-va.wav", rootMidi: 72, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 75, highMidi: 76, amplitude: 140, samples: [{ file: "III-Dsharp5-ba.wav", rootMidi: 75, tuneCents: -5 }, { file: "III-Dsharp5-va.wav", rootMidi: 75, tuneCents: -5 }] },
  { side: "treble", register: "III", lowMidi: 77, highMidi: 79, amplitude: 190, samples: [{ file: "III-Fsharp5-ba.wav", rootMidi: 78, tuneCents: 0 }, { file: "III-Fsharp5-va.wav", rootMidi: 78, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 80, highMidi: 82, amplitude: 150, samples: [{ file: "III-A5-ba.wav", rootMidi: 81, tuneCents: 0 }, { file: "III-A5-va.wav", rootMidi: 81, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 83, highMidi: 85, amplitude: 135, samples: [{ file: "III-C6-ba.wav", rootMidi: 84, tuneCents: -4 }, { file: "III-C6-va.wav", rootMidi: 84, tuneCents: -4 }] },
  { side: "treble", register: "III", lowMidi: 86, highMidi: 88, amplitude: 160, samples: [{ file: "III-Dsharp6-ba.wav", rootMidi: 87, tuneCents: 0 }, { file: "III-Dsharp6-va.wav", rootMidi: 87, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 89, highMidi: 91, amplitude: 170, samples: [{ file: "III-Fsharp6-ba.wav", rootMidi: 90, tuneCents: -4 }, { file: "III-Fsharp6-va.wav", rootMidi: 90, tuneCents: -4 }] },
  { side: "treble", register: "III", lowMidi: 92, highMidi: 94, amplitude: 200, samples: [{ file: "III-A6-ba.wav", rootMidi: 93, tuneCents: 0 }, { file: "III-A6-va.wav", rootMidi: 93, tuneCents: 0 }] },
  { side: "treble", register: "III", lowMidi: 95, highMidi: 96, amplitude: 160, samples: [{ file: "III-C7-ba.wav", rootMidi: 96, tuneCents: 0 }, { file: "III-C7-va.wav", rootMidi: 96, tuneCents: 0 }] },
];
